### Get Clients
GET http://localhost:3000/api/client/

### Get Client by ID
GET http://localhost:3000/api/client/66040c901664fef9b2a5f084
### Create Client
POST http://localhost:3000/api/client/
Content-Type: application/json

{
    "firstName": "xxx",
    "lastName": "xxx",
    "document": 10002,
    "email": "xxx@gmail.com",
    "phone": 312111,
    "address": "xxx"
}
### Update Client
PUT http://localhost:3000/api/client/660409ea0c01dcb593358a13
Content-Type: application/json

{
    "firstName": "Johnatan",
    "lastName": "Silva",
    "document": 10002,
    "email": "johnsilva@hotmail.com",
    "phone": 312111,
    "address": "Clle 14 - 14 12"
}

### Delete Client
DELETE http://localhost:3000/api/client/66040c901664fef9b2a5f084

### Get Supplier
GET http://localhost:3000/api/supplier/

### Get Supplier by ID
GET http://localhost:3000/api/supplier/6615832a4e17a666a4e85685

### Create Supplier
POST http://localhost:3000/api/supplier/
Content-Type: application/json

{
    "fullname": "Mongose INC",
    "address": "123 Street",
    "nit": 100890123,
    "email": "mongose@gmail.com",
    "phone": 312111
}

### Update Supplier
PUT http://localhost:3000/api/supplier/6615832a4e17a666a4e85685
Content-Type: application/json

{
    "fullname": "Docker",
    "address": "123 Avenue",
    "nit": 8009001,
    "email": "docker@gmail.com",
    "phone": 330123123
}

### Delete Client
DELETE http://localhost:3000/api/supplier/661580df25cee399dee7e5bf
